### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by KrzysztofSzewczyk** [KrzysztofSzewczyk/MEdit#5]
There is need to clean up code. It looks a little bit messy, because MainFrame file is too big and should be split into separate files / methods / classes.

**Comment by Obsidiam** [comment]
Yea, totally. Try to use patterns like: Builder, AbstractFactory with Flyweight.

**Comment by KrzysztofSzewczyk** [comment]
Partially resolved with #5.

**Comment by KrzysztofSzewczyk** [comment]
As #9 is open, this should be too, because it's not fully done yet.
