### ISSUE TITLE
Try to optimize memory usage

### ISSUE THREAD

**Issue by Obsidiam** [KrzysztofSzewczyk/MEdit#9]
After code cleanup do refactor so you can safely use -Xmx param; your app uses about 900MB of RAM, it is a little bit too much comparing to bigger NetBeans which after some hours of work needs about 1.3GB of RAM.

**Comment by KrzysztofSzewczyk** [comment]
@Obsidiam MEdit supports around 91 languages, while you need separate packs for NetBeans for every language.

Althrough, going to check it out.

**Comment by KrzysztofSzewczyk** [comment]
Resolved with lastest commits. Now MEdit doesn't consume more than 50MB of ram.
